Add classifier attribute to CustomerProvidedDocument
Nuvalence/dsgov-work-manager pull request #104
Opened 2023-05-24 14:21 UTC by deibys-nuvalence

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-05-24 19:05 UTC, dtsong commented
/gcbrun

2023-05-24 19:40 UTC, dtsong commented
Hi @deibys-nuvalence, for this specific PR, if you got a reviewer that grants approval from an app dev perspective, this PR can bypass the `app-work-manager-ephemeral-pr-trigger (dsgov-services)` check.

This is because I accidentally enabled the triggers before having the YAML files ready to go which leads to this situation where it's a false negative. Apologies for the disruption. Let me know via Slack if you have any questions.

2023-05-25 22:25 UTC, jgnuvalence requested changes
this looks good to me, I only left 1 comment

2023-05-25 22:25 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                                    .dataPath(transaction.getTransactionDefinition().getSchemaKey())
is this correct?, I think this should be the path of the document field, not the schemaKey

2023-05-25 23:10 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                                    .dataPath(transaction.getTransactionDefinition().getSchemaKey())
Hi @deibys-nuvalence and @jgnuvalence, I am currently working on this for my bug fix ticket.

2023-05-25 23:11 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                                    .dataPath(transaction.getTransactionDefinition().getSchemaKey())
ok makes sense, thank you @jcsuarezm

2023-05-25 23:12 UTC, jgnuvalence commented
you just need to update the branch with main

2023-05-26 14:01 UTC, jgnuvalence approved these changes

2023-05-26 14:11 UTC, merged