Dsg 774 create transaction notes model
Nuvalence/dsgov-work-manager pull request #123
Opened 2023-06-05 21:25 UTC by deibys-nuvalence

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-06-07 19:09 UTC, JayStGelais requested changes

2023-06-07 19:09 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +    public ResponseEntity<NoteModelResponse> getTransactionNote(UUID id, Integer noteId) {
Shouldn't these methods be on the `TransactionApiDelegate`?

2023-06-07 19:09 UTC, JayStGelais commented on helm/work-manager/cerbos-policies/note_resource.yaml
> +  resource: note
We should probably be enforcing permission checks on transaction notes specifically as we could have different permissions for other future note types.

2023-06-07 19:09 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/Note.java
> +@AccessResource("note")
I believe we will want to move permission configuration to specific sub-classes of note.

2023-06-07 19:09 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/Note.java
> +    @Column(name = "documents", columnDefinition = "jsonb")
Would it make more sense to have an attached document table with a FK on note instead of stuffing this in json?

2023-06-07 19:09 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/repository/NoteRepository.java
> +public interface NoteRepository extends JpaRepository<Note, Long> {
We probably only need a repository for the concrete `TransactionNote` type.

2023-06-07 19:18 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +    public ResponseEntity<NoteModelResponse> getTransactionNote(UUID id, Integer noteId) {
TransactionApiDelegate is growing in size too much. I thought it would better to have it separate  , also as "note" itself may be another concern

2023-06-07 19:32 UTC, deibys-nuvalence commented on helm/work-manager/cerbos-policies/note_resource.yaml
> +    - transaction-roles
done

2023-06-07 19:32 UTC, deibys-nuvalence commented on helm/work-manager/cerbos-policies/note_resource.yaml
> +        - transaction-submitter
removed transaction-submitter

2023-06-07 19:36 UTC, deibys-nuvalence commented on helm/work-manager/cerbos-policies/note_resource.yaml
> +  resource: note
done

2023-06-07 19:37 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/domain/Note.java
> +@AccessResource("note")
done

2023-06-07 19:42 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/domain/Note.java
> +    @Column(name = "documents", columnDefinition = "jsonb")
I am not sure, I thought about it but as practically it will only contain document ids and this fields does not seem to be editable. I thought a json column would fit
I guess in future if we want to query document id attached to a note, a table may be better
Shall I move this to a table ?

2023-06-07 21:41 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/repository/NoteRepository.java
> +public interface NoteRepository extends JpaRepository<Note, Long> {
done

2023-06-08 13:36 UTC, JayStGelais requested changes

2023-06-08 13:36 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/Note.java
> +    @Column(name = "documents", columnDefinition = "jsonb")
I think a table for this makes sense. There will eventually be unavoidable operations scenarios where we need to fix something by going into the database and a separate table will be easier to interact with.

2023-06-08 15:25 UTC, merged