Feature/dsg 781/record transaction note
Nuvalence/dsgov-work-manager pull request #135
Opened 2023-06-14 22:17 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-06-15 12:56 UTC, JayStGelais requested changes

2023-06-15 12:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +            noteService.postAuditEventForTransactionNote(
Instead of mapping the response back to a note, you could capture the return value of `noteService.createTransactionNote` to a local variable and pass that here. The double mapping here increases the potential for future bugs.

2023-06-15 12:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/models/NoteAddedAuditEventDto.java
> +public class NoteAddedAuditEventDto {
In regards to packaging, could we put audit event data in a separate package to make it clear that it is different than the main business models? Maybe an `auditevents` sub-package under models?

2023-06-15 12:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/NoteService.java
> +        Optional<Transaction> optionalTransaction =
You can save yourself a read of the transaction by using the created timestamp on the note for the event timestamp. I'm not sure that we are even updating lastupdatedTimestamp when we add a note, as it isn't an pdate to the actual transaction.

2023-06-15 14:43 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +            noteService.postAuditEventForTransactionNote(
Thank you Jay. The double mapping has been eliminated.

2023-06-15 14:45 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/models/NoteAddedAuditEventDto.java
> +public class NoteAddedAuditEventDto {
Thank you Jay. The class was moved to the auditevents sub-package.

2023-06-15 14:46 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/NoteService.java
> +        Optional<Transaction> optionalTransaction =
Thank you Jay. The timestamp is now obtained from the note.

2023-06-16 13:19 UTC, JayStGelais requested changes

2023-06-16 13:19 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +            log.error("Audit event was not published with exception {}", e);
Can we add more context to this message so that we have necessary info in the logs for remedy. I think we would need the transactionId, noteId and the fact this would have been a note created event.

Also, it's better to use the version of `log.error` that takes an exception as the 2nd argument instead of using string interpolation, because then it will properly marshall the stacktrace to JSON.

2023-06-16 14:46 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/NoteApiDelegateImpl.java
> +            log.error("Audit event was not published with exception {}", e);
Hi Jay, thank you. I have addressed the logging comment and added a test to validate the message is correct.

2023-06-16 15:48 UTC, JayStGelais approved these changes

2023-06-16 15:49 UTC, merged