Camunda managed submittedOn property
Nuvalence/dsgov-work-manager pull request #141
Opened 2023-06-20 14:47 UTC by Ortega-Dan

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-06-20 20:02 UTC, jgnuvalence approved these changes

2023-06-20 20:02 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +                // processInstanceId and status will be set in TransactionStatusUpdateDelegate, an
thank you for this Dan :)

2023-06-20 20:28 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                transaction.setSubmittedOn(OffsetDateTime.now());
How are you making sure that the submittedOn has the same value as the lastUpdatedTimestamp here?

2023-06-20 20:30 UTC, jgnuvalence requested changes
I think you are missing a logic to make sure that submittedOn and lastUpdatedTimestamp have the exact same value, please correct me if I'm wrong

2023-06-20 20:47 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                transaction.setSubmittedOn(OffsetDateTime.now());
Thank you for the check Julian, I believe it is not really a hard requirement since both are set at different times, but the lastUpdatedTimestamp gets updated on the save action triggered here in line 33, but captured by the UpdateTrackedEntityEventListener [here](https://github.com/Nuvalence/dsgov-work-manager/blob/3765545efebb8e0e6b48bb7c3a749f5be7ba6547/service/src/main/java/io/nuvalence/workmanager/service/domain/UpdateTrackedEntityEventListener.java#L39-L45). 
So those are in general just some nano, milis, or at most a couple of seconds away.
I anyway ping @JayStGelais for confirmation about the requirement.

2023-06-20 20:54 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                transaction.setSubmittedOn(OffsetDateTime.now());
I think we need to ensure they are kept in sync. Can we make sure that we apply the update to `lastUpdatedTimestamp`, prior to completing workflow tasks. Then we can have this line copy the `lastUpdatedTimestamp` to `submittedOn`

2023-06-20 20:57 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                transaction.setSubmittedOn(OffsetDateTime.now());
mm, nice. Thank you guys. I really didn't see it as a hard requirement but I can see there can be a use case on this, as a way to prove the last thing done at that time was the actual submit, and possibly other use cases. I'll check on it then.

2023-06-20 21:06 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                transaction.setSubmittedOn(OffsetDateTime.now());
I think we should take management of `lastUpdatedTimestamp` out of the JPA Event Listener, so that we can have access to the updated value prior to the flush of the Persistence Manager. This will also be important for consistent timestamps with audit events.

2023-06-21 12:46 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/UpdateTrackedEntityEventListener.java
> -
I don't think we should have moved the update to the date out of the listener, We should have just taken this listener off of transactions and manged these fields directly in the update method.

Sorry my last comment wasn't more clear.

2023-06-21 12:46 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        transaction.setLastUpdatedTimestamp(now);
This will lead to the lastUpdatedTimestamp being different than the timestamp on the audit events from this action. 

In the delegate we should just do this:

`transaction.setSubmittedOn(transaction.getLastUpdatedTimestamp());`

2023-06-21 17:40 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/UpdateTrackedEntityEventListener.java
> +        } catch (BeansException e) {
We should probably log a warning here if this actually happens.

2023-06-21 17:49 UTC, JayStGelais approved these changes

2023-06-21 17:54 UTC, jgnuvalence approved these changes

2023-06-21 17:56 UTC, merged