feature/DSG-783/audit-transaction-submitted
Nuvalence/dsgov-work-manager pull request #144
Opened 2023-06-21 23:09 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-06-22 19:28 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
Not sure but wonder if the name of this class may be more specific to what it does. Also if this is to handle submit events, this other class also exists [there](https://github.com/Nuvalence/dsgov-work-manager/blob/109e0c7aacf010b69ebad0de38391cea2509401d/service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java#L1-L42). Could we better use that one?. Triggering the discussion. What do you thing ?

2023-06-22 19:30 UTC, Ortega-Dan reviewed
Two questions in the single comment about the new Delegate

2023-06-22 20:16 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
Hi @Ortega-Dan, thank you. I believe the name was a design decision, as it was specified in the ticket's description, but I would also prefer using a different name.  @asultan001 @JayStGelais, please let me know if you would like a different name to be used or if it would be better to keep the current one.  
<img width="703" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/be51cbf1-aba9-4ec3-8593-87ae0e9d9f36">
Yes there are some changes in demo-config, found in this PR: https://github.com/Nuvalence/dsgov-demo-configurations/pull/14/files

2023-06-22 20:23 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
Besides the name of the class, I also would like to raise the question about using the [existing Delegate](https://github.com/Nuvalence/dsgov-work-manager/blob/109e0c7aacf010b69ebad0de38391cea2509401d/service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java#L1-L42) mentioned that handles submit events already. Setting the submittedOn timestamp and then sending a notification for a Delegate that handles actions for that event seem to be cohesive.

2023-06-22 20:34 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
hmm, so I'm not familiar with the design decision of why a new delegate was needed but I suspect that if the existing delegate is able to do all the work, we should just reuse the existing delegate. @JayStGelais probably needs to provide  some insights here but again if the current delegate is able to support everything we need, I don't see a need for a new one.

2023-06-23 02:01 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
As I'm reading this again, I'm not sure if submitting a transaction and sending a notification is desired for every audit event so it probably does make sense to separate that into different delegates but I'll let @JayStGelais answer that to be certain.

2023-06-26 17:54 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +            String summary =
Might make sense to make the summary configurable, perhaps using a handlebars syntax.

2023-06-26 19:40 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/AssignedToChangedAuditHandler.java
> +                    subjectUserId,
Thanks @JayStGelais, these were set to be both the id from the token, for this particular case.

2023-06-26 19:40 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +            String summary =
Handlerbars was introduced for this purpose.

2023-06-26 19:41 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +public class SimpleTransactionAuditEventDelegate implements JavaDelegate {
They have been kept separate, thank you!

2023-06-26 19:46 UTC, JayStGelais requested changes

2023-06-26 19:46 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +                    "Recording audit event for transaction with id {{transactionId}}.";
What I meant here regarding a handle bars capable template, was to pull this string from an extension property, which may include handlebar refernces to a set of available inputs.

makes sense to include transactionId, externalId, status, etc...

2023-06-26 19:48 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +                    "Recording audit event for transaction with id {{transactionId}}.";
Thank you @JayStGelais, will do that now.

2023-06-26 20:54 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/SimpleTransactionAuditEventDelegate.java
> +                    "Recording audit event for transaction with id {{transactionId}}.";
The change has been implemented @JayStGelais

2023-06-27 20:46 UTC, JayStGelais approved these changes

2023-06-27 20:47 UTC, merged