Feature/dsg 1026/enhance notes api
Nuvalence/dsgov-work-manager pull request #150
Opened 2023-06-30 20:08 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-03 12:20 UTC, JayStGelais requested changes

2023-07-03 12:20 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/models/BaseFilters.java
> -        switch (sortBy.toLowerCase(Locale.ENGLISH)) {
Wont this break transaction sorting? We probably need separate filter implementations for the different searchable entities.

2023-07-03 12:20 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/models/TransactionNoteFilters.java
> +public abstract class TransactionNoteFilters extends BaseFilters {
Why is there a subclass of this? Why not just include the implementation from `SearchTransactionNoteFilters` in this class? 

Not saying this is wrong, I just don't understand what we're planning for since, `SearchTransactionNoteFilters` is the only concrete implementation of this so far.

2023-07-04 16:10 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/models/BaseFilters.java
> -        switch (sortBy.toLowerCase(Locale.ENGLISH)) {
Hi @JayStGelais, the new code should be sufficient to make sure that transaction sorting is working as expected. I tested this, as shown here: 
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/c52673f1-8d52-42a0-9709-ba570fb9134c)
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/2266b7d9-c5b4-4434-aa64-38748aad7787)
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/e1243e4c-f055-4597-9957-c906f925bd01)
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/bafd1c52-a782-4596-ac03-e15f22bbb885)
I believe the implementation is flexible enough to maintain a single class, but please let me know if you believe it would be better to make this different for each searchable entity.

2023-07-04 16:10 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/models/TransactionNoteFilters.java
> +public abstract class TransactionNoteFilters extends BaseFilters {
Thank you Jay, the classes were unified to simplify the filtering implementation.

2023-07-05 14:13 UTC, JayStGelais approved these changes

2023-07-05 15:21 UTC, merged