Corrections buildNextPageUri
Nuvalence/dsgov-work-manager pull request #151
Opened 2023-07-04 22:28 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-05 15:40 UTC, JayStGelais requested changes

2023-07-05 15:40 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/PagingMetadataMapper.java
> +                    .scheme("https")
Instead of hardcoding this, we can get the values from various 'X-Forwarded-For' headers. Here is a good guide on setting this up:

https://tomgregory.com/spring-boot-behind-load-balancer-using-x-forwarded-headers/

2023-07-05 21:09 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/PagingMetadataMapper.java
> +                    .scheme("https")
Thanks @JayStGelais , this has been corrected

2023-07-06 13:21 UTC, asultan001 approved these changes
LGTM

2023-07-06 14:29 UTC, JayStGelais approved these changes

2023-07-06 14:29 UTC, merged