DSG-946: Make Notes Editable
Nuvalence/dsgov-work-manager pull request #152
Opened 2023-07-04 22:41 UTC by jgnuvalence

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-05 14:14 UTC, asultan001 commented on helm/work-manager/cerbos-policies/transaction_note_resource.yaml
> +    - actions: [ "update" ]
I think general Agents can still update notes, especially since we audit all changes.

2023-07-05 14:15 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/TransactionNoteStatusChangedAuditHandler.java
> +public class TransactionNoteStatusChangedAuditHandler implements AuditHandler<TransactionNote> {
Since we are auditing more than just a status change, I think simply calling this class a TransactionNoteChangedAuditHandler may be more appropriate.

2023-07-05 14:16 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/TransactionNoteStatusChangedAuditHandler.java
> +                                "Transaction note %s changed its dynamic data", transactionNoteId);
Notes don't have dynamic data so maybe reword this to say changed

2023-07-05 14:37 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/TransactionNoteStatusChangedAuditHandler.java
> +                                "Transaction note %s changed its dynamic data", transactionNoteId);
totally true, this was a copy-and-paste error, now it is corrected

2023-07-07 21:12 UTC, Ortega-Dan requested changes
Made some comments with minor changes that still improve codebase and usability. 
Everything looks great to me !

2023-07-07 21:12 UTC, Ortega-Dan commented on service/src/test/java/io/nuvalence/workmanager/service/service/NoteServiceTest.java
> +        when(noteTypeRepository.findByName(eq(testName))).thenReturn(Optional.of(noteType));
this eq here is linted by SonarQube to be not needed. Not a big deal but removing it helps avoid adding a new SQ lint
```suggestion
        when(noteTypeRepository.findByName(testName)).thenReturn(Optional.of(noteType));
```

2023-07-07 21:12 UTC, Ortega-Dan commented on service/src/test/java/io/nuvalence/workmanager/service/audit/TransactionNoteChangedAuditHandlerTest.java
> +        Assertions.assertTrue(newStateProperties.size() == 1);
SonarQube recommending Use assertEquals instead. Sometimes not willing to follow those but these changes are trivial and avoid adding SQ lints.

2023-07-07 22:32 UTC, jgnuvalence commented on swagger.yaml
> +    NoteModelRequest:
you are right, this was not really part of my code, it already existed but I made the change, good catch, thank you!

2023-07-07 22:33 UTC, jgnuvalence commented on service/src/test/java/io/nuvalence/workmanager/service/service/NoteServiceTest.java
> +        when(noteTypeRepository.findByName(eq(testName))).thenReturn(Optional.of(noteType));
thanks Dan, I'll try to keep these things in mind for future PRs, this is done

2023-07-07 22:33 UTC, jgnuvalence commented on service/src/test/java/io/nuvalence/workmanager/service/audit/TransactionNoteChangedAuditHandlerTest.java
> +        Assertions.assertTrue(newStateProperties.size() == 1);
thanks Dan, I'll try to keep these things in mind for future PRs, this is done

2023-07-10 16:21 UTC, Ortega-Dan approved these changes
:+1:

2023-07-10 16:22 UTC, merged