Feature/dsg 902/data validation
Nuvalence/dsgov-work-manager pull request #156
Opened 2023-07-07 22:20 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-11 23:22 UTC, jgnuvalence requested changes
I left some comments

2023-07-11 23:22 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/EntityMapper.java
> +                        element = DataConversionSupport.convert(element, dynaPropertyType);
this works for me for all cases i tried except for LocalDate:

schema:
```
{
      "name": "dateOfBirth",
      "type": "LocalDate",
      "attributeConfigurations": []
    }

```
Calling the endpoint
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/97063738/fb82be0b-90b1-4147-8793-14bb46b3dcec)

Result of the evaluation in this line is null, not an exception:
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/97063738/df760b0b-4c3b-4bb4-88fc-46704b237947)


The result is 200, but it should have been 400 and return a message saying that the format of dateOfBirth must be a date:
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/97063738/65107f12-f63d-43ce-b9e2-84359004d546)

2023-07-12 14:54 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                existing.put(entry.getKey(), entry.getValue());
Thanks @jgnuvalence! The conditions have been unified.

2023-07-12 14:56 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/EntityMapper.java
> +                            String.format("Invalid type for key: '%s'. It should be a Map.", key));
The message has been changed, now it uses composite object instead, as follows: 
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/15caecd4-3917-4dec-8e61-985dccd677be)

2023-07-12 14:58 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/EntityMapper.java
> +                        element = DataConversionSupport.convert(element, dynaPropertyType);
Thank you! This situation has been corrected by adding a null validation, this was tested as follows: 
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/3797e6ef-d395-43e4-a7d3-b08c4bf64623)
Document validation was also tested, as follows: 
![image](https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/65e63f8a-d949-4b4a-9c4e-cbc94c87a6a1)

2023-07-12 15:00 UTC, jgnuvalence approved these changes

2023-07-12 15:08 UTC, merged