Feature/dsg 1261/customer docs refactor
Nuvalence/dsgov-work-manager pull request #171
Opened 2023-07-24 23:00 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-24 23:02 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/CustomerProvidedDocument.java
> +    @OneToMany(fetch = FetchType.EAGER)
This was set to eagerly fetch, as it is not expected to have a significant amount of rejection reasons. This can be modified if desired.

2023-07-25 00:05 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/dynamicschema/attributes/Document.java
> +public class Document implements Serializable {
This was added to prevent the following bug that occurred when a Camunda task was completed: 
<img width="1301" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/a9ec1ff3-e5f4-4bb6-b24d-d194163e28f0">
<img width="1709" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/110409260/d2776bd4-9330-413f-b16c-596f014a9b6d">

2023-07-25 14:12 UTC, JayStGelais requested changes

2023-07-25 14:12 UTC, JayStGelais commented on service/src/main/resources/db/changelog/changelog/db.changelog-010.xml
> +        <dropColumn tableName="customer_provided_document" columnName="rejection_reason"/>
Before the drop could we insert rows into the new table based on this column. So we don't lose any historical data in dev?

2023-07-25 16:11 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/repository/RejectionReasonRepository.java
> +public interface RejectionReasonRepository
Thanks @JayStGelais, this repository was deleted.

2023-07-25 16:12 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        if (requestCustomerProvidedDocument.getRejectionReasons() != null
Thanks Jay, this has been corrected.

2023-07-25 16:13 UTC, jcsuarezm commented on service/src/main/resources/db/changelog/changelog/db.changelog-010.xml
> +        <dropColumn tableName="customer_provided_document" columnName="rejection_reason"/>
Thanks, a changeset was added to insert this before dropping the column.

2023-07-25 18:59 UTC, jgnuvalence approved these changes

2023-07-25 19:50 UTC, merged