DSG-1179/add-enumerations-endpoints
Nuvalence/dsgov-work-manager pull request #173
Opened 2023-07-25 17:11 UTC by afcalderonm

## Description
create new endpoints to get all the enums information, also group all the enums into a new package for better organization

## Motivation and Context
The  endpoints will serve up infrequently changing system configuration the front end will need to populate forms with allowed values.

## Areas for Focus

## How Has This Been Tested?
added test to validate the behavior also tested locally using postman

## Screenshots (if appropriate):

test behavior to get all enums info
<img width="1289" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/112962842/c792cdd3-298d-430f-9729-0e570099ae6d">

test behavior to get an enum by id 
<img width="1297" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/112962842/80e47b78-2c4e-404b-9f56-7ea96694bcd2">

test behavior when a given id does not exists
<img width="827" alt="image" src="https://github.com/Nuvalence/dsgov-work-manager/assets/112962842/111b8616-fa90-4b1d-a451-8a7cd9ed11be">

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-07-26 23:08 UTC, asultan001 commented on swagger.yaml
> +              type: integer
@JayStGelais I'm curious of your opinion on this but in my opinion, from an API point of view, using integers is not as intuitive as the enum label.

2023-07-26 23:08 UTC, asultan001 commented on swagger.yaml
> +              type: integer
Same point as before

2023-07-26 23:09 UTC, asultan001 commented on swagger.yaml
> +          type: integer
I don't think we should change this

2023-07-26 23:09 UTC, asultan001 commented on swagger.yaml
> +          type: integer
I don't think we should change this

2023-07-27 14:31 UTC, JayStGelais requested changes

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/AssignedToChangedAuditHandler.java
> +import io.nuvalence.workmanager.service.enums.AuditActivityType;
It was unnecessary and I believe undesired to refacfor all of our enums by moving them to an enum package. It is more approriate to leve enums in the domain packages with the other business objects they relate to.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +        ENUM_MAP.put("transaction-note-types", NoteTypes.class);
Note types should be read from the table they are configured in, not a new enum.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +        ENUM_MAP.put("review-statuses", ReviewStatus.class);
key should be `document-review-statuses`

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/enums/TransactionPriority.java
> +    ONE(1, "Low"),
I think it would be better to base the enum symbol names on the english language value, ie `Low`, `Medium`, `High` and `Urgent`. Instead of `ONE`, `TWO`, `THREE` and `FOUR`.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/enums/SupportedTypes.java
> +    STRING(String.class, "String Type Class"),
Also lets make the enum symbol names match the display names (do not need to be all caps) removing spaces as necessary.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +                .priority(2) // default to medium TODO: check with FE dropdown to ingest that
Use the enum here for readability. Instead of "2", this could be `TransactionPriority.Medium.getValue()`.

Or to take it a step further we could add an overloaded method to the builder that accepts the enum.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/mapper/TransactionMapperTest.java
> +                        .priority(1)
Let's get the integer values from the enum so that the code more clearly documents logic.

2023-07-27 14:31 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionFactoryTest.java
> +                        .priority(2)
tagging this spot with the desire to use the enum

2023-07-27 14:31 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionServiceTest.java
> +                        .priority(List.of(1))
tagging this spot with the desire to use the enum

2023-07-27 14:31 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionStatusUpdateDelegateTest.java
> +                        .priority(1)
tagging this spot with the desire to use the enum

2023-07-27 14:31 UTC, JayStGelais commented on swagger.yaml
> +              type: integer
I think we can/should internalize the use of integers and use the labels at the API. The integers in the database will allow for logical query sorting, but we can use the enum type in the JPA entity and just configure persistence to write the integer into the database.

That said, if we ever want to implement client side sorting we will need to write a custom sort method that uses the mapped integer values from the priority enum.

2023-08-02 01:46 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionStatusUpdateDelegateTest.java
> +                        .priority(1)
Change Applied

2023-08-02 01:46 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionServiceTest.java
> +                        .priority(List.of(1))
Change Applied

2023-08-02 01:47 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/service/TransactionFactoryTest.java
> +                        .priority(2)
Change Applied

2023-08-02 01:47 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/mapper/TransactionMapperTest.java
> +                        .priority(1)
Change Applied

2023-08-02 01:47 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +                .priority(2) // default to medium TODO: check with FE dropdown to ingest that
Change Applied

2023-08-02 01:47 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/enums/TransactionPriority.java
> +    ONE(1, "Low"),
Change Applied

2023-08-02 01:47 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/enums/SupportedTypes.java
> +    STRING(String.class, "String Type Class"),
Change Applied

2023-08-02 02:11 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +        ENUM_MAP.put("transaction-note-types", NoteTypes.class);
change applied and now the note types are read from the database values

2023-08-02 02:40 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/audit/transaction/AssignedToChangedAuditHandler.java
> +import io.nuvalence.workmanager.service.enums.AuditActivityType;
i just rollback the changes

2023-08-02 05:51 UTC, afcalderonm commented on swagger.yaml
> +              type: integer
revert the change to be a String again and manage it internally

2023-08-02 05:51 UTC, afcalderonm commented on swagger.yaml
> +          type: integer
revert the change to be a String again and manage it internally

2023-08-02 05:51 UTC, afcalderonm commented on swagger.yaml
> +          type: integer
revert the change to be a String again and manage it internally

2023-08-02 05:52 UTC, afcalderonm commented on swagger.yaml
> +              type: integer
revert the change to be a String again and manage it internally

2023-08-02 12:27 UTC, JayStGelais requested changes

2023-08-02 12:27 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +        enums.add(buildNoteTypes());
I think this is going to add a copy of the note types everytime you call this endpoint.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +    public ResponseEntity<List<EnumerationResponseModel>> getEnumerations() {
The response type here should be a map of enum types to list of enums. The top level strucutre should not be a list.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +    List<EnumerationResponseModel> enums;
We shouldn't use shared state to build a response. This won't be thread safe.

2023-08-02 12:27 UTC, JayStGelais commented on swagger.yaml
> +      type: array
Should be an object with keys equal to the enumeration types.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/RejectionReasonType.java
> +    POOR_QUALITY("POOR_QUALITY", "String Value"),
Not the literal value "String Value", the previous comment meant a plain string value of the constant. Such as

POOR_QUALITY -> Poor Quality

2023-08-02 12:27 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +    private Integer priority;
Can we try to make this an instance of the enum. We might have to customize the hibernate mapping to store the integer values.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/enums/DocumentRejectReasonTest.java
> +package io.nuvalence.workmanager.service.enums;
Should probably move the test calss back to the package the main class is in.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/enums/DocumentStatusTest.java
> +package io.nuvalence.workmanager.service.enums;
Should probably move the test calss back to the package the main class is in.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/enums/RejectionReasonTest.java
> +package io.nuvalence.workmanager.service.enums;
Should probably move the test calss back to the package the main class is in.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/enums/ReviewStatusTest.java
> +package io.nuvalence.workmanager.service.enums;
Should probably move the test calss back to the package the main class is in.

2023-08-02 12:27 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/workmanager/service/enums/TransactionPriorityTest.java
> +package io.nuvalence.workmanager.service.enums;
Should probably move the test calss back to the package the main class is in.

2023-08-02 18:57 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/enums/TransactionPriorityTest.java
> +package io.nuvalence.workmanager.service.enums;
moved

2023-08-02 18:57 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/enums/ReviewStatusTest.java
> +package io.nuvalence.workmanager.service.enums;
moved

2023-08-02 18:57 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/enums/RejectionReasonTest.java
> +package io.nuvalence.workmanager.service.enums;
moved

2023-08-02 18:57 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/enums/DocumentStatusTest.java
> +package io.nuvalence.workmanager.service.enums;
moved

2023-08-02 18:57 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/workmanager/service/enums/DocumentRejectReasonTest.java
> +package io.nuvalence.workmanager.service.enums;
moved

2023-08-02 18:58 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/RejectionReasonType.java
> +    POOR_QUALITY("POOR_QUALITY", "String Value"),
changed

2023-08-08 06:42 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/ReviewStatus.java
> +    NEW("NEW", "String Value"),
Change Applied

2023-08-08 06:51 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +        enums.add(buildNoteTypes());
I just modify the share stated and try it and it does not create a copy when you call the endpoint

2023-08-08 06:52 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +    List<EnumerationResponseModel> enums;
i just removed the share state

2023-08-08 14:56 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +    public ResponseEntity<List<EnumerationResponseModel>> getEnumerations() {
change made and now it is a map

2023-08-08 14:56 UTC, afcalderonm commented on swagger.yaml
> +      type: array
change made

2023-08-09 13:25 UTC, JayStGelais requested changes

2023-08-09 13:25 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +    @Enumerated(EnumType.ORDINAL)
We don't want to store the ordinal because it can change if we insert new values, thus changing the meaning of data in the database.

We want to use the intvalue configured on the enum. The best way to do this would be to write a converter for the `TransactionPriority` enum type. 

This link has soe info on how to do that (section 4): https://www.baeldung.com/jpa-persisting-enums-in-jpa

2023-08-09 13:25 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/TransactionsApiDelegateImpl.java
> +        List<Integer> priortiyIntegerList = new ArrayList<>();
We shouldn't need to work with integers here. This should be written in terms of the enum.

2023-08-09 13:25 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/RejectionReasonType.java
> +    POOR_QUALITY("Poor Quality", "String Value"),
These lables are still incorrect. This line should read:

`POOR_QUALITY("POOR_QUALITY", "Poor Quality"),`

2023-08-09 13:25 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/ReviewStatus.java
> +    NEW("New", "String Value"),
Similar to the comment on `RejectionReasonType` these lables need to be fixed.

2023-08-09 13:25 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +    @Enumerated(EnumType.ORDINAL)
Note: when you write the converter it belonds in the `io.nuvalence.workmanager.service.utils.jpa` package along side the existing converter.

2023-08-10 03:54 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/RejectionReasonType.java
> +    POOR_QUALITY("Poor Quality", "String Value"),
Fixed

2023-08-10 03:54 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/customerprovideddocument/ReviewStatus.java
> +    NEW("New", "String Value"),
Fixed

2023-08-10 03:58 UTC, afcalderonm commented on swagger.yaml
> +    EnumerationResponseModel:
Changes were applied to match the desired response

2023-08-10 03:59 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EnumsApiDelegateImpl.java
> +    private EnumerationResponseModel buildEnumResponseModel(
fixed

2023-08-10 03:59 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +    @Enumerated(EnumType.ORDINAL)
Converter was applied to avoid using ORDINAL

2023-08-10 03:59 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/TransactionsApiDelegateImpl.java
> +        List<Integer> priortiyIntegerList = new ArrayList<>();
the List was change to be handle in terms of the enum

2023-08-10 13:58 UTC, merged