Feature/dsg 1092/pending customer provided documents
Nuvalence/dsgov-work-manager pull request #183
Opened 2023-08-02 17:27 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-08-02 17:29 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> -        Set<UUID> documentsToRemove =
Customer provided documents that were not sent in the update request were being inactivated, going against the partial update functionality, this was corrected.

2023-08-02 17:32 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                    transaction.getData().set(pendingCustomerProvidedDocument.getDataPath(), new Document(pendingCustomerProvidedDocument.getId()));
It was necessary to add the Pending documents to the transaction path.

2023-08-02 18:48 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                                        .getData()
Adds the documents to the transaction data.

2023-08-03 13:39 UTC, JayStGelais requested changes

2023-08-03 13:39 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> -        Set<UUID> documentsToRemove =
We will still need to remove (mark inactive) documents when they are overwritten. When we see an update that sneds a differeint document ID for an existing path.

2023-08-03 13:39 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                setDocumentsFromPendingToNew(transaction);
This doesn't really belong in the submission step of the workflow. This status change should happen when we see the document ID of a pending document appear in dynamic form data.

2023-08-03 22:06 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> -        Set<UUID> documentsToRemove =
Thanks Jay, this has been added in line 314.

2023-08-03 22:08 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionSubmitDelegate.java
> +                setDocumentsFromPendingToNew(transaction);
Thanks Jay, this has been corrected.

2023-08-04 12:30 UTC, JayStGelais requested changes

2023-08-04 12:30 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                    throw new BusinessLogicException(
Not sure that we want to throw an exception here. While I suspect this won't happen under normal usage, it could happen after we implement version management for configuration and include features for version migration of live transactions.

I think it would be better to update the path attribute of the `CustomerProvidedDocument` in this case.

2023-08-04 16:34 UTC, JayStGelais approved these changes

2023-08-04 16:48 UTC, dtsong approved these changes

2023-08-04 16:49 UTC, merged