Bug/dsg 1326/formio validation changes
Nuvalence/dsgov-work-manager pull request #202
Opened 2023-08-22 18:55 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-09-04 21:05 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                    transactionDefinition.getFormConfigurationKey(task, userType, context);
the getFormConfigurationKey already returns the default one if nothing matches. And it has unit tests checking that. So this could do it this way or the other. (So this is just nitpicking, not needing change if not wanted).

2023-09-04 21:09 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/FormConfigurationService.java
> +                        .label(label)
Not sure if this was coordinated with the FrontEnd, but changing this from error message to error name seems to be not appropriate since calles to this method, like this one: https://github.com/Nuvalence/dsgov-work-manager/blob/181751787463f63e2643b1e072088112f6a108c2/service/src/main/java/io/nuvalence/workmanager/service/service/FormConfigurationService.java#L188-L192 do actually provide a message for the error instead of a name.

2023-09-04 21:11 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/FormConfigurationMapper.java
> +                                                .errorName(message)
same here about error name.

2023-09-04 21:17 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/config/exceptions/model/NuvalenceFormioValidationExItem.java
> +    private String label;
We could use error name in places where we need to use it, but seems like there are places were error message is appropriate (as a longer and more detailed description string). Im ok with adding label.

2023-09-04 21:26 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/utils/formconfig/formio/NuvalenceFormioValidator.java
> +
since this is done in 2 different places, and since this is a util class, should this be modularized as a public method including the subsequent call to transformCameCaseToSeparateWords method ?

2023-09-04 21:28 UTC, Ortega-Dan reviewed
Minimal changes may be needed. I approve on the approach to achieve the validation and the submit of data.

2023-09-04 21:42 UTC, Ortega-Dan requested changes
I approve on the approach to achieve the validation and the submit of data. But after a post-review conversation with Juan, those comments are confirmed as needed.

2023-09-04 23:00 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +                    transactionDefinition.getFormConfigurationKey(task, userType, context);
Thanks @Ortega-Dan, this has been addressed by calling the method directly.

2023-09-04 23:02 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/FormConfigurationService.java
> +                        .label(label)
Thanks Dan, the message property has been added back. The front end feature related to this ticket mainly uses the name and calculates the label and id itself.

2023-09-04 23:02 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/FormConfigurationMapper.java
> +                                                .errorName(message)
Thanks, this has been corrected.

2023-09-04 23:03 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/config/exceptions/model/NuvalenceFormioValidationExItem.java
> +    private String label;
Thanks Dan, this class was left as it was before.

2023-09-04 23:03 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/utils/formconfig/formio/NuvalenceFormioValidator.java
> +
This method was removed as now labels are being calculated in the front end.

2023-09-05 00:35 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/FormConfigurationMapper.java
> +        }
This seems to be no longer in use but was not removed.

2023-09-05 00:43 UTC, Ortega-Dan requested changes
Only one comment pending on not removed code.

2023-09-05 14:13 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/mapper/FormConfigurationMapper.java
> +        }
Thanks @Ortega-Dan, this has been removed.

2023-09-05 14:21 UTC, Ortega-Dan approved these changes
👍 :shipit:

2023-09-07 18:25 UTC, jgnuvalence approved these changes

2023-09-07 18:40 UTC, merged