Feature/dsg 1510/dashboard ordering
Nuvalence/dsgov-work-manager pull request #234
Opened 2023-09-15 16:53 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-09-18 14:59 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionDefinitionSetOrderService.java
> +        repository.findAll().stream()
would this be better to delete all elements in the table ?
My understanding you will replace the whole current list with the new list ?

2023-09-18 15:38 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/TransactionDefinitionSet.java
> +
as you are going to query the ordering not through the transaction definition set,  is it necessary to have to have this eager loading entity here ?

2023-09-18 15:38 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/TransactionDefinitionSet.java
> +    private TransactionDefinitionSetOrder transactionDefinitionSetOrder;
as you are going to query the ordering not through the transaction definition set, is it necessary to have to have this eager loading entity here ?

2023-09-18 15:49 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/DashboardConfigurationService.java
> -        return (List<DashboardConfiguration>) dashboardConfigurationRepository.findAll();
not sure as it is not clear in requirements ...
the returned list should be driven based on the ordering of transaction definition sets ?

It is hard to interpret in the requirements if "Returns an ordered list of dashboard configurations" means only returned dashboard specified in the transaction set order list or the ordering refers to something else ?

2023-09-18 16:15 UTC, JayStGelais requested changes

2023-09-18 21:23 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionDefinitionSetOrderService.java
> +        repository.findAll().stream()
Thanks Jay and Deibys, a delete all has been introduced as well as some db constraint changes to allow a simpler code here.

2023-09-18 21:23 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/TransactionDefinitionSet.java
> +    private TransactionDefinitionSetOrder transactionDefinitionSetOrder;
Thanks Jay and Deibys,this was modified to use @Formula to only load the sort order. This was chosen in place of implementing via join in order to prioritize code maintainability and simplicity as the performance impact was not considered significant. The later option would have required additional service and repository level code that would have added unnecessary complexity.

2023-09-18 21:23 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/DashboardConfigurationService.java
> -        return (List<DashboardConfiguration>) dashboardConfigurationRepository.findAll();
Thank Deibys, this has been validated and is the expected behavior.

2023-09-18 21:24 UTC, jcsuarezm commented on helm/work-manager/cerbos-policies/dashboard_configuration_resource.yaml
> +        - transaction-config-admin
Thanks Jay, the cerbos configuration has been made more granular to allow viewing for both roles, but update is only allowed for the config admin.

2023-09-18 21:25 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/service/DashboardConfigurationService.java
> +        transactionDefinitionSetOrderService.getTransactionDefinitionSetOrder().stream()
Thanks Jay, this has been simplified by using the proposed validation, reducing the calls to the db.

2023-09-19 12:52 UTC, JayStGelais approved these changes

2023-09-19 14:37 UTC, merged