Bug/DSG-2481/Return 200 when no document processors present on process enqueue
Nuvalence/dsgov-work-manager pull request #343
Opened 2023-12-12 17:57 UTC by kives-nu

## Description
Updating document processor logic to return 200 when no processors present. 

## Motivation and Context
When no document processors are attached to a document, the product guidance is to return 200 when we attempt to process, instead of an error code. Prior to these changes, a 403 would be thrown as the schema parsing function would through a null pointer error instead of returning a list of empty processors. This PR addresses that null pointer exception and adds a test to verify it. There is a corresponding document manager PR as well, to return 200 instead of 400 when it receives no processors. 

## Areas for Focus
I also made a change to the values.local.yml in the helm charts. I am not sure if this should be kept or not. It appears to me like it was an error, dsgov-document-manager does not align with the other values in the local.yml. This particular line broke the ability of my local minikube work manager to communicate my minikube document manager. Since the default name for the local service is document-manager, without the dsgov. 

However, the name has been dsgov-document-manager for 7 months. I would have thought this breaks all communicate between local WM and local DM for everyone, but I am assuming it is not given how long the change has been in. If anyone has any insight into why and if the values.local.yml should be kept the way it is, that would be great. 

## How Has This Been Tested?
If you follow the steps to reproduce on the ticket (you may need to modify a schema to have no document processors first), you will see 403 errors. If you deploy this fix and reproduce, the document processing endpoint will return 200 with an empty list instead. Additionally, there is a new unit test to verify the new null check. 

## Types of changes
Patch
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

- [x] I have confirmed all acceptance criteria defined by the story have been met

2023-12-12 18:54 UTC, kives-nu commented on helm/work-manager/values.local.yaml
> +  DOCUMENT_MANAGEMENT_BASE_URL: "http://document-management/dm"
See PR description for discussion on this change

2023-12-12 19:07 UTC, jgnuvalence approved these changes

2023-12-12 19:07 UTC, jgnuvalence commented on helm/work-manager/values.local.yaml
> +  DOCUMENT_MANAGEMENT_BASE_URL: "http://document-management/dm"
Personally, this works well for me with the dsgov prefix, in my local I can see that docman has that prefix in the service release name, but the other apps do not have it, I think the fix should be done there before changing it here, but if this it works for you gets me confused

2023-12-12 19:07 UTC, jgnuvalence commented on helm/work-manager/values.local.yaml
> +  DOCUMENT_MANAGEMENT_BASE_URL: "http://document-management/dm"
btw now we are communicating with docman eventually, so anyway this is not going to be used, we probably need a ticket to remove this API client

2023-12-12 19:19 UTC, kives-nu commented on helm/work-manager/values.local.yaml
> +  DOCUMENT_MANAGEMENT_BASE_URL: "http://document-management/dm"
Makes sense, I can revert the change since then. 

I am running my DM service through cloudclode and attaching a debugger, not sure if that's somehow impacting the service name

2023-12-12 19:30 UTC, jgnuvalence requested changes
reviewing the docman PR I realize that probably the best approach is to simply not send the event to start document processing when there is no processor, this way you don't need to make any changes to document-management

2023-12-14 14:17 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/TransactionsApiDelegateImpl.java
> +        if (processorsNames.isEmpty()) {
I think we still need to save the customer-provided documents even if they don't have processors, I think we just need to avoid executing:
documentManagementService.initiateDocumentProcessing(...)

2023-12-14 17:25 UTC, jgnuvalence approved these changes

2023-12-14 19:41 UTC, merged