Feature/dsg 2497/employer user links
Nuvalence/dsgov-work-manager pull request #366
Opened 2023-12-19 18:38 UTC by kives-nu

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-12-21 17:23 UTC, kives-nu commented on service/src/main/java/io/nuvalence/workmanager/service/models/IndividualFilters.java
>  import io.nuvalence.workmanager.service.domain.profile.Individual;
Changes to this file were necessary because I modified the behavior of the userManagementClient function

2023-12-21 17:24 UTC, kives-nu commented on service/src/main/java/io/nuvalence/workmanager/service/usermanagementapi/UserManagementClient.java
>      @Override
The primary motivation for these changes in particular was to change the pagination behavior of the function to get all relevant pages so no users were left behind. It was also easier to return a list of userDTOs object that wasn't wrapped in a page.

2023-12-21 19:28 UTC, Ortega-Dan commented on swagger.yaml
> +        createdBy:
It is recommended to have the response bring all the properties from the request like in: https://github.com/Nuvalence/dsgov-work-manager/blob/bdba636ada877e7ec816f6cad4d3a574ad0270a8/swagger.yaml#L2150-L2167

2023-12-21 19:30 UTC, Ortega-Dan commented on swagger.yaml
> +    EmployerProfileLinkRequest:
We also tend to call this ones ...Model to clearly differentiate from the internal objects.

2023-12-21 22:10 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/usermanagementapi/UserManagementClient.java
>      @Override
:+1: Nice.

2023-12-21 22:14 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/controllers/EmployerProfilesApiDelegateImpl.java
> +        }
I just believe we do not really need this final else, since it is already null in line 109.

2023-12-21 22:18 UTC, Ortega-Dan commented on service/src/main/resources/db/changelog/changelog/db.changelog-034.xml
> +            <column name="user_id" type="varchar(255)">
is there a reason why this is not uuid ?

2023-12-21 22:22 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/EmployerUserLinkService.java
> +    private final UserManagementClient userManagementClient;
nit: looks like this line is not really needed here.

2023-12-21 22:26 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/models/EmployerUserLinkFilters.java
> +@Getter
about the errors in the pipeline, it is possible it is due to several SonarQube warnings. like kissing javadocs in this class. This class has several warnings and you can tackle them locally if you install a pluging called SonarLint (not sure if it is the same name in intellij but I use that one in vscode) which may help to identify warnings. 
I also know some pre-existing files may have the same issues. But better if we see if this is related since warnings have special weight in new code.

2023-12-21 22:30 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/domain/profile/EmployerUserLink.java
> +        if (!(o instanceof EmployerUserLink link)) return false;
here are some checkstyle errors, those should pop if you run locally: `./gradlew clean build`

2023-12-21 22:32 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/domain/profile/EmployerUserLink.java
> +        if (!(o instanceof EmployerUserLink link)) return false;
You could also use a checkstyle plugin. For vscode I use: https://marketplace.visualstudio.com/items?itemName=rianadon.vscode-java-checkstyle, but that is just a helper, running the gradlew clean build should be enough since it produces a report. and the output will have a link to the local html report.

2023-12-21 22:43 UTC, Ortega-Dan commented on service/src/test/java/io/nuvalence/workmanager/service/models/IndividualFiltersTest.java
This test file is broken in several tests due to the need to adjust this.

2023-12-21 22:46 UTC, Ortega-Dan requested changes
Some comments

2023-12-22 15:46 UTC, kives-nu commented on swagger.yaml
> +        createdBy:
Do I not have these underneath ? One line 2199 - 2210 ?

2023-12-22 15:51 UTC, kives-nu commented on service/src/main/resources/db/changelog/changelog/db.changelog-034.xml
> +            <column name="user_id" type="varchar(255)">
I had issues with hibernate not passing UUID objects as such, but converting them to strings. So if this was UUID, all my repository methods were failing. 

I figured we must have seen this problem before so I dug around the transaction entity and found this 

```
    @Setter
    @Column(name = "transaction_definition_id", length = 36, nullable = false)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    private UUID transactionDefinitionId;
 ``` 
 
 Where we are treating a UUID as a string at the DB layer, presumably because of the same issue I was encountering.

2023-12-22 15:53 UTC, kives-nu commented on swagger.yaml
> +    EmployerProfileLinkRequest:
I renamed to EmployerProfileLinkRequestModel, is that what you meant ?

2023-12-22 17:02 UTC, Ortega-Dan commented on service/src/main/resources/db/changelog/changelog/db.changelog-034.xml
> +            <column name="user_id" type="varchar(255)">
Ok. Thanks :+1:

2023-12-22 17:04 UTC, Ortega-Dan commented on swagger.yaml
> +    EmployerProfileLinkRequest:
Right. Thanks. As mentioned, this is more just to keep the pattern and to the actual differentiation.

2023-12-22 17:07 UTC, Ortega-Dan commented on swagger.yaml
> +        createdBy:
This is more about the usage of allOf to bring properties from another object and then extend adding new ones.

2023-12-22 17:10 UTC, Ortega-Dan commented on service/src/test/java/io/nuvalence/workmanager/service/models/IndividualFiltersTest.java
Solved

2023-12-22 17:13 UTC, Ortega-Dan approved these changes

2023-12-22 17:13 UTC, Ortega-Dan commented
Approved but it is not compiling in my local:
![Uploading image.png…]()

2023-12-22 19:51 UTC, merged