DSGOV-368: added the external_id field to the transaction table
Nuvalence/dsgov-work-manager pull request #37
Opened 2023-04-12 21:58 UTC by jgnuvalence

DSGOV-368: added the external_id field to the transaction table, which is based on a db sequence, which is ZBase32 encoded

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-04-13 18:28 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/repository/TransactionRepository.java
> +    @Query(value = "SELECT nextval('transaction_sequence')", nativeQuery = true)
if this query is selecting the nextval for the transaction sequence .... (question continues in next file) ....

2023-04-13 18:31 UTC, Ortega-Dan approved these changes
approval with context question

2023-04-13 18:31 UTC, Ortega-Dan commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +        sequenceNumber = sequenceNumber + 1; // increment the sequence value
... is this increment needed ? Just asking as nitpicking, but I believe if it is fine I am anyway approving.

2023-04-13 19:02 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        return repository.save(factory.createTransaction(definition, sequenceValue));
Please take my feedback with a grain of salt and I think it may be best to have @JayStGelais review this or perhaps ask one of the engineers at MPWR how that was done in their case but having the service layer be responsible for having to provide the sequence number seems like the wrong place as it requires the client to understand the internals of the domain too much and it can also lead to creating wrong transactions if the proper sequence number is not provided.  I also thought that this would have been a slightly bigger code that was encoded from a Guid but reading the architecture proposal it did seem like we wanted to do it based on a db sequence.

2023-04-13 19:17 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/repository/TransactionRepository.java
> +    @Query(value = "SELECT nextval('transaction_sequence')", nativeQuery = true)
thanks @Ortega-Dan, I had 2 approaches and I kept one, but it seems that I did not clean up the code correctly, it is already corrected

2023-04-13 19:17 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        return repository.save(factory.createTransaction(definition, sequenceValue));
Hello @asultan001, if it's okay with you we can leave this PR open until Monday, from my point of view, the service is responsible for calling the DAOs/Repositories to obtain or save the data, and also for calling the factory providing the correct information. From that point of view I think it's fine. We can have a discussion about this on Monday if that's okay with you?

2023-04-13 19:44 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        return repository.save(factory.createTransaction(definition, sequenceValue));
Sounds good @jgnuvalence , let's discuss more on Monday when @JayStGelais is back. I just want to avoid potential errors due to miss-use of the library. Someone reusing the same sequence number or something to that extent.

2023-04-17 15:48 UTC, JayStGelais requested changes

2023-04-17 15:48 UTC, JayStGelais commented on service/build.gradle
> +	implementation 'com.sandinh:zbase32-commons-codec_2.12:1.0.0'
I'm nervous using this 3rd party libarary. It isn't published under any open source license and it hasn't been touched in 5 years. If we discover a bug or security vulnerability it is unlikely the maintainers will address it. 

The ZBase algorithm is vers straight forward. I think we should just implement it internally. We can use the code in this library as a reference if needed.

2023-04-17 15:48 UTC, JayStGelais commented on service/build.gradle
> +	implementation 'com.sandinh:zbase32-commons-codec_2.12:1.0.0'
I got this version of a function from ChatGPT. We would want to write some unit tests for it to verify it is correct.

```
public static String encodeZBase32(int number) {
    final String base32Alphabet = "ybndrfg8ejkmcpqxot1uwisza345h769";
    final int base = base32Alphabet.length();
    StringBuilder sb = new StringBuilder();
    int remainder;

    do {
        remainder = number % base;
        sb.append(base32Alphabet.charAt(remainder));
        number /= base;
    } while (number > 0);

    return sb.reverse().toString();
}
```

2023-04-17 15:48 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +    public Transaction createTransaction(final TransactionDefinition definition, Long sequenceValue)
I think we can encapsulate this logic inside the factory and not require callers to fetch the sequence number.

2023-04-17 15:48 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        return repository.save(factory.createTransaction(definition, sequenceValue));
Per coment above, I think moving the sequence management logic down into `TransactionFactory` makes sense.

2023-04-17 15:48 UTC, JayStGelais commented on service/src/main/resources/db/changelog/changelog-master.xml
> +        <createSequence sequenceName="transaction_sequence" startValue="10" incrementBy="1" />
Can we be a little more descriptive with this name. Maybe `transaction_external_id_sequence`. We may have future yet to be identified use cases for sequences.

2023-04-17 16:13 UTC, jgnuvalence commented on service/build.gradle
> +	implementation 'com.sandinh:zbase32-commons-codec_2.12:1.0.0'
sounds good Jay, totally agreed

2023-04-17 22:33 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionService.java
> +        return repository.save(factory.createTransaction(definition, sequenceValue));
this is done

2023-04-17 22:33 UTC, jgnuvalence commented on service/build.gradle
> +	implementation 'com.sandinh:zbase32-commons-codec_2.12:1.0.0'
this is done

2023-04-17 22:33 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/service/TransactionFactory.java
> +    public Transaction createTransaction(final TransactionDefinition definition, Long sequenceValue)
this is done

2023-04-17 22:33 UTC, jgnuvalence commented on service/src/main/resources/db/changelog/changelog-master.xml
> +        <createSequence sequenceName="transaction_sequence" startValue="10" incrementBy="1" />
this is done

2023-04-18 17:50 UTC, JayStGelais requested changes

2023-04-18 17:50 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/utils/ZBase32Utility.java
> +    public static String encode(String inputText) {
This encoder should be taking integers (should probably support both int and long.

This logic is also very difficult to follow. 

Let me take a stab at implementing this. I think we can make this much simpler. I would use bitmasks and bit shifting to pull out the 5 bit chunks of integer data.

2023-04-19 16:58 UTC, JayStGelais approved these changes

2023-04-19 17:34 UTC, JayStGelais approved these changes

2023-04-19 17:34 UTC, merged