dsg-2847: feedback sentiment analysis
Nuvalence/dsgov-work-manager pull request #421
Opened 2024-02-06 15:02 UTC by jgnuvalence

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2024-02-08 17:12 UTC, JayStGelais requested changes

2024-02-08 17:12 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/SentimentOverrideSetDelegate.java
> +public class SentimentOverrideSetDelegate implements JavaDelegate {
Our delegates should be general purpose building blocks and should never need to directly refer to attributes defined in a dynamic schema.

2024-02-08 17:12 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/UpdateFeedbackDataDelegate.java
> +            String sentiment = data.get("sentiment");
Same concern here. Let's meet offline if you need help structuring a workflow around this that uses general purpose building blocks.

2024-02-08 17:12 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/VertexAIPromptDelegate.java
> +            data.put("sentiment", sentiment);
This delegate is closer to general purpose. The fields for input and output should be configured by extension properties. The delegate should not have knowledge of specific schema configuraitons, the workflow configuration on the other hand can.

2024-02-08 17:12 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/jobs/DraftFeedbackTransactionCleanerJob.java
> +public class DraftFeedbackTransactionCleanerJob {
Lets leave this off for now. I'm not sure this is the approach  we want to take to data cleanup. We should put more thought into this part of the architecture before we move forward with a solution.

2024-02-08 17:12 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/repository/TransactionRepository.java
> +    @Query(
This query should not have knowledge of specific transaction configurations.

2024-02-09 14:17 UTC, JayStGelais requested changes

2024-02-09 14:17 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/DynamicDataUpdaterDelegate.java
> +            Map<String, String> data = (Map) execution.getVariable("data");
Does this actually do what you intend it to do? I believe the "data" variable is always set to the dynamic data from the transaction as last loaded in `TransactionTaskService.completeTask()`

2024-02-09 14:17 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/DynamicDataUpdaterDelegate.java
> +public class DynamicDataUpdaterDelegate implements JavaDelegate {
Also, I think we could have an even more generic delegate that updates transaction data (core and/or dynamic) by mapping process variables to paths in the tranaction, using BeanUtils to apply the change. 

Example: Imagine we have previous steps that invoke an LLM to analyze sentiment, categorize data in the transaction and determine a priority based on those 2 inputs using a DMN tables. Each previous step adds a process variable with their results (variables: sentiment, category and priority). We then call this delgate with extension properties that look like this:

transactionDataUpdate.sentiment = data.sentiment 
transactionDataUpdate.category = data.category 
transactionDataUpdate.priority = priority

Where the extension property names are the format `transactionDataUpdate.{processVariable}` and their value is the path to write the data to.

2024-02-09 14:17 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/TransactionDataContextSetterDelegate.java
> +            log.warn("TransactionDataContextSetterDelegate - transactionId not found");
may want to include the transaction Id in the log message.

2024-02-09 14:17 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/VertexAIPromptDelegate.java
> +        execution.setVariable("vertexai.response", vertexAIResponse);
Should probably allow the result variable name to be configured as an extension property so that we can have multiple LLM steps that wont overwrite each other's results. We could also use this hardcoded value as a default if the workflow omits the result property.

2024-02-12 20:24 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/SentimentOverrideSetDelegate.java
> +public class SentimentOverrideSetDelegate implements JavaDelegate {
this was done

2024-02-12 20:24 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/VertexAIPromptDelegate.java
> +            data.put("sentiment", sentiment);
this was done

2024-02-12 20:26 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/DynamicDataUpdaterDelegate.java
> +            Map<String, String> data = (Map) execution.getVariable("data");
yes, this was working, but a refactor was done based on our meeting on Friday

2024-02-12 20:28 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/DynamicDataUpdaterDelegate.java
> +public class DynamicDataUpdaterDelegate implements JavaDelegate {
this was done

2024-02-12 20:29 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/TransactionDataContextSetterDelegate.java
> +            log.warn("TransactionDataContextSetterDelegate - transactionId not found");
since transaction id is null I don't think we need this, look at the line 34

2024-02-12 20:30 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/VertexAIPromptDelegate.java
> +        execution.setVariable("vertexai.response", vertexAIResponse);
this was done

2024-02-12 20:53 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/feedback/UpdateFeedbackDataDelegate.java
> +            String sentiment = data.get("sentiment");
this was done

2024-02-12 20:53 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/jobs/DraftFeedbackTransactionCleanerJob.java
> +public class DraftFeedbackTransactionCleanerJob {
this was done

2024-02-12 20:53 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/repository/TransactionRepository.java
> +    @Query(
this was done

2024-02-13 15:35 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/workmanager/service/camunda/delegates/TransactionDataUpdaterDelegate.java
> +        this.variablePathsMap =
this was done

2024-02-13 15:49 UTC, JayStGelais approved these changes

2024-02-13 15:51 UTC, merged