Dsg 193 customer document
Nuvalence/dsgov-work-manager pull request #53
Opened 2023-04-24 21:10 UTC by jcsuarezm

## Description

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-04-25 17:12 UTC, asultan001 requested changes

2023-04-25 17:12 UTC, asultan001 commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +            mappedBy = "transactionId",
not sure if we are using underscores (_) instead of camelCasing for columns names.

2023-04-25 17:12 UTC, asultan001 commented on service/src/test/java/io/nuvalence/workmanager/service/mapper/TransactionMapperTest.java
> +                        .customerProvidedDocuments(new ArrayList<>());
Do we have a add test to cover this in the assertions?

2023-04-25 21:47 UTC, jcsuarezm commented on swagger.yaml
> +        - schameKey
Typo corrected

2023-04-25 21:49 UTC, jcsuarezm commented on service/src/main/java/io/nuvalence/workmanager/service/domain/transaction/Transaction.java
> +            mappedBy = "transactionId",
Thanks, the relationship between tables has been adjusted.

2023-04-25 21:51 UTC, jcsuarezm commented on service/src/test/java/io/nuvalence/workmanager/service/mapper/TransactionMapperTest.java
> +                        .customerProvidedDocuments(new ArrayList<>());
I have enriched the test to make it go beyond an empty list. The logic for adding CustomerProidedDocuments to Transactions is not yet implemented, I believe it will be within the scope of future tickets.

2023-04-25 21:52 UTC, jcsuarezm commented on swagger.yaml
> +        - R1
I put these values as placeholders. There is not a clear set of rejection reasons we would like to allowed, as far as I know. @JayStGelais, please correct me if I missed the desired enumeration.

2023-04-26 13:25 UTC, asultan001 approved these changes
LGTM

2023-04-26 13:26 UTC, asultan001 commented on swagger.yaml
> +        - R1
Just waiting for @JayStGelais to provide confirmation of the rejection reasons for the time being. If we are ok with these for now please resolve this conversation so that this PR can merge.

2023-04-26 14:01 UTC, JayStGelais requested changes

2023-04-26 16:22 UTC, jcsuarezm commented on swagger.yaml
> +        - R1
Thanks, the new values were added

2023-04-26 18:32 UTC, JayStGelais approved these changes

2023-04-26 20:57 UTC, dtsong approved these changes

2023-04-26 20:58 UTC, merged